### GET request to example server
GET http://localhost:8080/api/products
Authorization: Bearer {{auth_token}}

### POST request to create a new product
POST http://localhost:8080/api/products
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "name": "Togg T10X",
    "price": 1453,
    "description": "The first domestic electric car of Turkey.",
    "barcode": "107114531923",
    "sku": null
}

### PUT request to update an existing product
PUT http://localhost:8080/api/products/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Updated Togg T10X",
  "price": 1918,
  "description": "The first domestic electric car of Turkey.",
  "barcode": null,
  "sku": "107114531923"
}

### DELETE request to remove a product
DELETE http://localhost:8080/api/products/1

### POST create a new user (register)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### POST login and save token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

> {% client.global.set("auth_token", response.body.token); %}
