spring:
  application:
    name: "product-api"

  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: myapp_user
    password: secure_password_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
